version: "3"

networks:
  laravel:
  
services:
  proxy:
    build:
      context: ./nginx
    ports: 
      - 8080:80
      - 8081:81
    volumes:
      - ./backend:/var/www
    depends_on:
      - frontend
      - backend
      - db
    restart: "unless-stopped"
    networks:
      - laravel
  db:
    image: mysql:5.7
    ports:
      - 3301:3306
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    env_file:
      - .env
    networks:
      - laravel
    restart: "unless-stopped"

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
      - /var/www/node_modules
      - /var/www/vendor
    depends_on:
      - db
    networks:
      - laravel
    restart: "unless-stopped"
    
  frontend:
    build: ./frontend/
    env_file:
      - ./.env
    volumes:
      - ./frontend:/var/www/client:cached
    ports:
      - 3006:3000
    depends_on:
      - db
      - backend
    networks:
      - laravel
    restart: "unless-stopped"

networks:
  laravel:
    driver: bridge